Fix dataframe helpers on Windows
 - make get_tty_size() returning 0 when called without terminal (e.g. when redirecting output)
 - check for nonzero return value of `_isatty()`. According to the doc, `_isatty` returns a nonzero value if the descriptor is associated with a character device. Otherwise, `_isatty` returns 0.
 - in `dataframe_helpers.cxx`, don't use `f1.root` and `f2.root`, they are already used in `dataframe_nodes.cxx` and might conflict when running tests concurrently

This fixes the following errors on Windows:
```
unknown file: error: C++ exception with description "string too long" thrown in the test body.
[  FAILED  ] RDFHelpers.ProgressHelper_Existence_ST (5009 ms)
[ RUN      ] RDFHelpers.ProgressHelper_Existence_MT
C:\ROOT-CI\src\core\testsupport\src\TestSupport.cxx(77): error: Failed
Received unexpected diagnostic of severity 5000 at 'TFile::TFile' reading 'could not delete C:\ROOT-CI\build\tree\dataframe\test\f2.root (errno: 13) Permission denied'.
```